import React, { useState } from 'react'
import type { Meta, StoryObj } from '@storybook/react'
import { VStack, HStack, Text, Box } from '@opengov/cds-primitives'
import { AiDisclaimer, type AiDisclaimerProps } from './AiDisclaimer'

// ---------------------------------------------------------------------------
// Meta
// ---------------------------------------------------------------------------

const meta: Meta<typeof AiDisclaimer> = {
  title: 'Patterns/AiDisclaimer',
  component: AiDisclaimer,
  argTypes: {
    variant: {
      control: 'select',
      options: ['inline', 'banner'],
    },
    dismissible: { control: 'boolean' },
    message: { control: 'text' },
  },
}

export default meta
type Story = StoryObj<typeof AiDisclaimer>

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

function SectionLabel({ children }: { children: string }) {
  return (
    <Text variant="h5" color="$colorSecondary">
      {children}
    </Text>
  )
}

// ---------------------------------------------------------------------------
// 1. InlineVariant
// ---------------------------------------------------------------------------

export const InlineVariant: Story = {
  name: 'Inline Variant',
  render: () => (
    <VStack gap="$4" padding="$4">
      <SectionLabel>Inline Disclaimer (default)</SectionLabel>
      <AiDisclaimer variant="inline" />

      <SectionLabel>Inline with Custom Message</SectionLabel>
      <AiDisclaimer
        variant="inline"
        message="Responses are generated by AI and may not reflect official government policy."
      />
    </VStack>
  ),
}

// ---------------------------------------------------------------------------
// 2. BannerVariant
// ---------------------------------------------------------------------------

export const BannerVariant: Story = {
  name: 'Banner Variant',
  render: () => (
    <VStack gap="$4">
      <VStack padding="$4">
        <SectionLabel>Banner Disclaimer (full-width)</SectionLabel>
      </VStack>

      <AiDisclaimer variant="banner" />

      <VStack padding="$4" gap="$4">
        <SectionLabel>Banner with Custom Message</SectionLabel>
      </VStack>

      <AiDisclaimer
        variant="banner"
        message="This summary was generated using AI. For binding information, consult the official documentation."
      />
    </VStack>
  ),
}

// ---------------------------------------------------------------------------
// 3. Dismissible
// ---------------------------------------------------------------------------

function DismissibleDemo() {
  const [inlineVisible, setInlineVisible] = useState(true)
  const [bannerVisible, setBannerVisible] = useState(true)

  return (
    <VStack gap="$4" padding="$4">
      <SectionLabel>Dismissible Inline</SectionLabel>
      {inlineVisible ? (
        <AiDisclaimer
          variant="inline"
          dismissible
          onDismiss={() => setInlineVisible(false)}
        />
      ) : (
        <Box
          padding="$3"
          borderRadius={8}
          backgroundColor="#F5F5F5"
          alignItems="center"
        >
          <Text variant="body3" color="$colorSecondary">
            Inline disclaimer dismissed.
          </Text>
          <Box
            marginTop="$2"
            paddingHorizontal="$3"
            paddingVertical="$1.5"
            borderRadius={4}
            backgroundColor="#EBF0FF"
            onPress={() => setInlineVisible(true)}
          >
            <Text variant="caption" color="#1E55FF" fontWeight="$semibold">
              Reset
            </Text>
          </Box>
        </Box>
      )}

      <SectionLabel>Dismissible Banner</SectionLabel>
      {bannerVisible ? (
        <AiDisclaimer
          variant="banner"
          dismissible
          onDismiss={() => setBannerVisible(false)}
        />
      ) : (
        <Box
          padding="$3"
          borderRadius={8}
          backgroundColor="#F5F5F5"
          alignItems="center"
        >
          <Text variant="body3" color="$colorSecondary">
            Banner disclaimer dismissed.
          </Text>
          <Box
            marginTop="$2"
            paddingHorizontal="$3"
            paddingVertical="$1.5"
            borderRadius={4}
            backgroundColor="#EBF0FF"
            onPress={() => setBannerVisible(true)}
          >
            <Text variant="caption" color="#1E55FF" fontWeight="$semibold">
              Reset
            </Text>
          </Box>
        </Box>
      )}
    </VStack>
  )
}

export const Dismissible: Story = {
  name: 'Dismissible',
  render: () => <DismissibleDemo />,
}

// ---------------------------------------------------------------------------
// 4. WithLearnMore
// ---------------------------------------------------------------------------

function LearnMoreDemo() {
  const [tapped, setTapped] = useState(false)

  return (
    <VStack gap="$4" padding="$4">
      <SectionLabel>With Learn More Link</SectionLabel>
      <AiDisclaimer
        variant="inline"
        onLearnMore={() => setTapped(true)}
        learnMoreUrl="https://opengov.com/ai-disclaimer"
      />

      {tapped && (
        <Box padding="$3" borderRadius={8} backgroundColor="#E8F5E9">
          <Text variant="body3" color="#388E3C">
            "Learn more" was tapped. In production this would navigate to the AI disclaimer page.
          </Text>
        </Box>
      )}

      <SectionLabel>Banner with Learn More</SectionLabel>
      <AiDisclaimer
        variant="banner"
        onLearnMore={() => setTapped(true)}
        learnMoreUrl="https://opengov.com/ai-disclaimer"
      />

      <SectionLabel>All Options Combined</SectionLabel>
      <AiDisclaimer
        variant="inline"
        dismissible
        onDismiss={() => {}}
        onLearnMore={() => setTapped(true)}
        learnMoreUrl="https://opengov.com/ai-disclaimer"
        message="This response was generated using artificial intelligence. Results should be verified before use in official proceedings."
      />
    </VStack>
  )
}

export const WithLearnMore: Story = {
  name: 'With Learn More',
  render: () => <LearnMoreDemo />,
}
